// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionApproval.Infrastructure.Persistence;

#nullable disable

namespace TransactionApproval.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713145646_UpgradeOutboxProcessorModel")]
    partial class UpgradeOutboxProcessorModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionApproval.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeadLetteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LeasedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "DeadLetteredAtUtc", "AvailableAtUtc", "LeasedUntilUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("TransactionApproval.Domain.Entities.Region", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Code");

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "IL",
                            Name = "Israel",
                            TimeZoneId = "Asia/Jerusalem"
                        },
                        new
                        {
                            Code = "FR",
                            Name = "France",
                            TimeZoneId = "Europe/Paris"
                        },
                        new
                        {
                            Code = "US-East",
                            Name = "United States (East)",
                            TimeZoneId = "America/New_York"
                        },
                        new
                        {
                            Code = "US-West",
                            Name = "United States (West)",
                            TimeZoneId = "America/Los_Angeles"
                        },
                        new
                        {
                            Code = "JP",
                            Name = "Japan",
                            TimeZoneId = "Asia/Tokyo"
                        },
                        new
                        {
                            Code = "GB",
                            Name = "United Kingdom",
                            TimeZoneId = "Europe/London"
                        },
                        new
                        {
                            Code = "DE",
                            Name = "Germany",
                            TimeZoneId = "Europe/Berlin"
                        },
                        new
                        {
                            Code = "CY",
                            Name = "Cyprus",
                            TimeZoneId = "Asia/Nicosia"
                        },
                        new
                        {
                            Code = "IT",
                            Name = "Italy",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Code = "AU",
                            Name = "Australia (Sydney)",
                            TimeZoneId = "Australia/Sydney"
                        });
                });

            modelBuilder.Entity("TransactionApproval.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LocalTransactionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("SubmittedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RegionCode");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("TransactionApproval.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TransactionApproval.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("TransactionApproval.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
